new Text: ArivenaLogoTD[20];

Create_ArivenaLogoTD()
{
    ArivenaLogoTD[0] = TextDrawCreate(322.000, 3.000, "\\");
    TextDrawLetterSize(ArivenaLogoTD[0], 0.509, 1.398);
    TextDrawAlignment(ArivenaLogoTD[0], TEXT_DRAW_ALIGN_LEFT);
    TextDrawColour(ArivenaLogoTD[0], -7232257);
    TextDrawSetShadow(ArivenaLogoTD[0], 0);
    TextDrawSetOutline(ArivenaLogoTD[0], 0);
    TextDrawBackgroundColour(ArivenaLogoTD[0], 150);
    TextDrawFont(ArivenaLogoTD[0], TEXT_DRAW_FONT_1);
    TextDrawSetProportional(ArivenaLogoTD[0], true);

    ArivenaLogoTD[1] = TextDrawCreate(324.000, 3.000, "\\");
    TextDrawLetterSize(ArivenaLogoTD[1], 0.509, 1.398);
    TextDrawAlignment(ArivenaLogoTD[1], TEXT_DRAW_ALIGN_LEFT);
    TextDrawColour(ArivenaLogoTD[1], -7232257);
    TextDrawSetShadow(ArivenaLogoTD[1], 0);
    TextDrawSetOutline(ArivenaLogoTD[1], 0);
    TextDrawBackgroundColour(ArivenaLogoTD[1], 150);
    TextDrawFont(ArivenaLogoTD[1], TEXT_DRAW_FONT_1);
    TextDrawSetProportional(ArivenaLogoTD[1], true);

    ArivenaLogoTD[2] = TextDrawCreate(322.000, 15.000, "\\");
    TextDrawLetterSize(ArivenaLogoTD[2], 0.509, 1.398);
    TextDrawAlignment(ArivenaLogoTD[2], TEXT_DRAW_ALIGN_LEFT);
    TextDrawColour(ArivenaLogoTD[2], -7232257);
    TextDrawSetShadow(ArivenaLogoTD[2], 0);
    TextDrawSetOutline(ArivenaLogoTD[2], 0);
    TextDrawBackgroundColour(ArivenaLogoTD[2], 150);
    TextDrawFont(ArivenaLogoTD[2], TEXT_DRAW_FONT_1);
    TextDrawSetProportional(ArivenaLogoTD[2], true);

    ArivenaLogoTD[3] = TextDrawCreate(324.000, 15.000, "\\");
    TextDrawLetterSize(ArivenaLogoTD[3], 0.509, 1.398);
    TextDrawAlignment(ArivenaLogoTD[3], TEXT_DRAW_ALIGN_LEFT);
    TextDrawColour(ArivenaLogoTD[3], -7232257);
    TextDrawSetShadow(ArivenaLogoTD[3], 0);
    TextDrawSetOutline(ArivenaLogoTD[3], 0);
    TextDrawBackgroundColour(ArivenaLogoTD[3], 150);
    TextDrawFont(ArivenaLogoTD[3], TEXT_DRAW_FONT_1);
    TextDrawSetProportional(ArivenaLogoTD[3], true);

    ArivenaLogoTD[4] = TextDrawCreate(312.000, 1.000, "/");
    TextDrawLetterSize(ArivenaLogoTD[4], 0.888, 2.598);
    TextDrawTextSize(ArivenaLogoTD[4], 16.000, 0.000);
    TextDrawAlignment(ArivenaLogoTD[4], TEXT_DRAW_ALIGN_LEFT);
    TextDrawColour(ArivenaLogoTD[4], -7232257);
    TextDrawSetShadow(ArivenaLogoTD[4], 0);
    TextDrawSetOutline(ArivenaLogoTD[4], 0);
    TextDrawBackgroundColour(ArivenaLogoTD[4], 150);
    TextDrawFont(ArivenaLogoTD[4], TEXT_DRAW_FONT_1);
    TextDrawSetProportional(ArivenaLogoTD[4], true);

    ArivenaLogoTD[5] = TextDrawCreate(327.000, 4.000, "/");
    TextDrawLetterSize(ArivenaLogoTD[5], 0.888, 2.5986);
    TextDrawAlignment(ArivenaLogoTD[5], TEXT_DRAW_ALIGN_LEFT);
    TextDrawColour(ArivenaLogoTD[5], -72322576);
    TextDrawSetShadow(ArivenaLogoTD[5], 06);
    TextDrawSetOutline(ArivenaLogoTD[5], 06);
    TextDrawBackgroundColour(ArivenaLogoTD[5], 1506);
    TextDrawFont(ArivenaLogoTD[5], TEXT_DRAW_FONT_1);
    TextDrawSetProportional(ArivenaLogoTD[5], true);

    ArivenaLogoTD[6] = TextDrawCreate(312.000, 1.000, "/");
    TextDrawLetterSize(ArivenaLogoTD[6], 0.888, 2.598);
    TextDrawAlignment(ArivenaLogoTD[6], TEXT_DRAW_ALIGN_LEFT);
    TextDrawColour(ArivenaLogoTD[6], -7232257);
    TextDrawSetShadow(ArivenaLogoTD[6], 0);
    TextDrawSetOutline(ArivenaLogoTD[6], 0);
    TextDrawBackgroundColour(ArivenaLogoTD[6], 150);
    TextDrawFont(ArivenaLogoTD[6], TEXT_DRAW_FONT_1);
    TextDrawSetProportional(ArivenaLogoTD[6], true);

    ArivenaLogoTD[7] = TextDrawCreate(327.000, 4.000, "/");
    TextDrawLetterSize(ArivenaLogoTD[7], 0.888, 2.598);
    TextDrawAlignment(ArivenaLogoTD[7], TEXT_DRAW_ALIGN_LEFT);
    TextDrawColour(ArivenaLogoTD[7], -7232257);
    TextDrawSetShadow(ArivenaLogoTD[7], 0);
    TextDrawSetOutline(ArivenaLogoTD[7], 0);
    TextDrawBackgroundColour(ArivenaLogoTD[7], 150);
    TextDrawFont(ArivenaLogoTD[7], TEXT_DRAW_FONT_1);
    TextDrawSetProportional(ArivenaLogoTD[7], true);

    ArivenaLogoTD[8] = TextDrawCreate(299.000, 31.000, "T");
    TextDrawLetterSize(ArivenaLogoTD[8], 0.246, 1.399);
    TextDrawTextSize(ArivenaLogoTD[8], -23.500, -24.000);
    TextDrawAlignment(ArivenaLogoTD[8], TEXT_DRAW_ALIGN_LEFT);
    TextDrawColour(ArivenaLogoTD[8], -1);
    TextDrawSetShadow(ArivenaLogoTD[8], 0);
    TextDrawSetOutline(ArivenaLogoTD[8], 0);
    TextDrawBackgroundColour(ArivenaLogoTD[8], 255);
    TextDrawFont(ArivenaLogoTD[8], TEXT_DRAW_FONT_2);
    TextDrawSetProportional(ArivenaLogoTD[8], true);

    ArivenaLogoTD[9] = TextDrawCreate(306.000, 31.000, "H");
    TextDrawLetterSize(ArivenaLogoTD[9], 0.246, 1.399);
    TextDrawTextSize(ArivenaLogoTD[9], -23.500, -24.000);
    TextDrawAlignment(ArivenaLogoTD[9], TEXT_DRAW_ALIGN_LEFT);
    TextDrawColour(ArivenaLogoTD[9], -1);
    TextDrawSetShadow(ArivenaLogoTD[9], 0);
    TextDrawSetOutline(ArivenaLogoTD[9], 0);
    TextDrawBackgroundColour(ArivenaLogoTD[9], 255);
    TextDrawFont(ArivenaLogoTD[9], TEXT_DRAW_FONT_2);
    TextDrawSetProportional(ArivenaLogoTD[9], true);

    ArivenaLogoTD[10] = TextDrawCreate(315.000, 33.798, "ld_dual:white");
    TextDrawLetterSize(ArivenaLogoTD[10], 0.307, 1.700);
    TextDrawTextSize(ArivenaLogoTD[10], 5.000, 1.500);
    TextDrawAlignment(ArivenaLogoTD[10], TEXT_DRAW_ALIGN_LEFT);
    TextDrawColour(ArivenaLogoTD[10], -1);
    TextDrawSetShadow(ArivenaLogoTD[10], 0);
    TextDrawSetOutline(ArivenaLogoTD[10], 0);
    TextDrawBackgroundColour(ArivenaLogoTD[10], 255);
    TextDrawFont(ArivenaLogoTD[10], TEXT_DRAW_FONT_SPRITE_DRAW);
    TextDrawSetProportional(ArivenaLogoTD[10], true);

    ArivenaLogoTD[11] = TextDrawCreate(315.000, 37.500, "ld_dual:white");
    TextDrawLetterSize(ArivenaLogoTD[11], 0.307, 1.700);
    TextDrawTextSize(ArivenaLogoTD[11], 5.000, 1.500);
    TextDrawAlignment(ArivenaLogoTD[11], TEXT_DRAW_ALIGN_LEFT);
    TextDrawColour(ArivenaLogoTD[11], -1);
    TextDrawSetShadow(ArivenaLogoTD[11], 0);
    TextDrawSetOutline(ArivenaLogoTD[11], 0);
    TextDrawBackgroundColour(ArivenaLogoTD[11], 255);
    TextDrawFont(ArivenaLogoTD[11], TEXT_DRAW_FONT_SPRITE_DRAW);
    TextDrawSetProportional(ArivenaLogoTD[11], true);

    ArivenaLogoTD[12] = TextDrawCreate(315.000, 41.000, "ld_dual:white");
    TextDrawLetterSize(ArivenaLogoTD[12], 0.307, 1.700);
    TextDrawTextSize(ArivenaLogoTD[12], 5.000, 1.500);
    TextDrawAlignment(ArivenaLogoTD[12], TEXT_DRAW_ALIGN_LEFT);
    TextDrawColour(ArivenaLogoTD[12], -1);
    TextDrawSetShadow(ArivenaLogoTD[12], 0);
    TextDrawSetOutline(ArivenaLogoTD[12], 0);
    TextDrawBackgroundColour(ArivenaLogoTD[12], 255);
    TextDrawFont(ArivenaLogoTD[12], TEXT_DRAW_FONT_SPRITE_DRAW);
    TextDrawSetProportional(ArivenaLogoTD[12], true);

    ArivenaLogoTD[13] = TextDrawCreate(321.000, 46.000, "V");
    TextDrawLetterSize(ArivenaLogoTD[13], 0.246, -1.549);
    TextDrawTextSize(ArivenaLogoTD[13], -34.500, 69.000);
    TextDrawAlignment(ArivenaLogoTD[13], TEXT_DRAW_ALIGN_LEFT);
    TextDrawColour(ArivenaLogoTD[13], -1);
    TextDrawSetShadow(ArivenaLogoTD[13], 0);
    TextDrawSetOutline(ArivenaLogoTD[13], 0);
    TextDrawBackgroundColour(ArivenaLogoTD[13], 255);
    TextDrawFont(ArivenaLogoTD[13], TEXT_DRAW_FONT_2);
    TextDrawSetProportional(ArivenaLogoTD[13], true);

    ArivenaLogoTD[14] = TextDrawCreate(324.000, 39.500, "ld_dual:white");
    TextDrawLetterSize(ArivenaLogoTD[14], 0.307, 1.7002);
    TextDrawTextSize(ArivenaLogoTD[14], 2.000, 1.5002);
    TextDrawAlignment(ArivenaLogoTD[14], TEXT_DRAW_ALIGN_LEFT);
    TextDrawColour(ArivenaLogoTD[14], -12);
    TextDrawSetShadow(ArivenaLogoTD[14], 02);
    TextDrawSetOutline(ArivenaLogoTD[14], 02);
    TextDrawBackgroundColour(ArivenaLogoTD[14], 2552);
    TextDrawFont(ArivenaLogoTD[14], TEXT_DRAW_FONT_SPRITE_DRAW);
    TextDrawSetProportional(ArivenaLogoTD[14], true);

    ArivenaLogoTD[15] = TextDrawCreate(327.000, 31.000, "T");
    TextDrawLetterSize(ArivenaLogoTD[15], 0.246, 1.399);
    TextDrawTextSize(ArivenaLogoTD[15], -23.500, -24.000);
    TextDrawAlignment(ArivenaLogoTD[15], TEXT_DRAW_ALIGN_LEFT);
    TextDrawColour(ArivenaLogoTD[15], -1);
    TextDrawSetShadow(ArivenaLogoTD[15], 0);
    TextDrawSetOutline(ArivenaLogoTD[15], 0);
    TextDrawBackgroundColour(ArivenaLogoTD[15], 255);
    TextDrawFont(ArivenaLogoTD[15], TEXT_DRAW_FONT_2);
    TextDrawSetProportional(ArivenaLogoTD[15], true);

    ArivenaLogoTD[16] = TextDrawCreate(335.000, 33.798, "ld_dual:white");
    TextDrawLetterSize(ArivenaLogoTD[16], 0.307, 1.700);
    TextDrawTextSize(ArivenaLogoTD[16], 5.000, 1.500);
    TextDrawAlignment(ArivenaLogoTD[16], TEXT_DRAW_ALIGN_LEFT);
    TextDrawColour(ArivenaLogoTD[16], -1);
    TextDrawSetShadow(ArivenaLogoTD[16], 0);
    TextDrawSetOutline(ArivenaLogoTD[16], 0);
    TextDrawBackgroundColour(ArivenaLogoTD[16], 255);
    TextDrawFont(ArivenaLogoTD[16], TEXT_DRAW_FONT_SPRITE_DRAW);
    TextDrawSetProportional(ArivenaLogoTD[16], true);

    ArivenaLogoTD[17] = TextDrawCreate(335.000, 37.500, "ld_dual:white");
    TextDrawLetterSize(ArivenaLogoTD[17], 0.307, 1.700);
    TextDrawTextSize(ArivenaLogoTD[17], 5.000, 1.500);
    TextDrawAlignment(ArivenaLogoTD[17], TEXT_DRAW_ALIGN_LEFT);
    TextDrawColour(ArivenaLogoTD[17], -1);
    TextDrawSetShadow(ArivenaLogoTD[17], 0);
    TextDrawSetOutline(ArivenaLogoTD[17], 0);
    TextDrawBackgroundColour(ArivenaLogoTD[17], 255);
    TextDrawFont(ArivenaLogoTD[17], TEXT_DRAW_FONT_SPRITE_DRAW);
    TextDrawSetProportional(ArivenaLogoTD[17], true);

    ArivenaLogoTD[18] = TextDrawCreate(335.000, 41.000, "ld_dual:white");
    TextDrawLetterSize(ArivenaLogoTD[18], 0.307, 1.700);
    TextDrawTextSize(ArivenaLogoTD[18], 5.000, 1.500);
    TextDrawAlignment(ArivenaLogoTD[18], TEXT_DRAW_ALIGN_LEFT);
    TextDrawColour(ArivenaLogoTD[18], -1);
    TextDrawSetShadow(ArivenaLogoTD[18], 0);
    TextDrawSetOutline(ArivenaLogoTD[18], 0);
    TextDrawBackgroundColour(ArivenaLogoTD[18], 255);
    TextDrawFont(ArivenaLogoTD[18], TEXT_DRAW_FONT_SPRITE_DRAW);
    TextDrawSetProportional(ArivenaLogoTD[18], true);

    ArivenaLogoTD[19] = TextDrawCreate(342.000, 31.000, "R");
    TextDrawLetterSize(ArivenaLogoTD[19], 0.277, 1.399);
    TextDrawTextSize(ArivenaLogoTD[19], -23.500, -24.000);
    TextDrawAlignment(ArivenaLogoTD[19], TEXT_DRAW_ALIGN_LEFT);
    TextDrawColour(ArivenaLogoTD[19], -1);
    TextDrawSetShadow(ArivenaLogoTD[19], 0);
    TextDrawSetOutline(ArivenaLogoTD[19], 0);
    TextDrawBackgroundColour(ArivenaLogoTD[19], 255);
    TextDrawFont(ArivenaLogoTD[19], TEXT_DRAW_FONT_2);
    TextDrawSetProportional(ArivenaLogoTD[19], true);
}

Show_ArivenaLogoTD(playerid)
{
    for(new i = 0; i < 20; i++)
    {
        TextDrawShowForPlayer(playerid, ArivenaLogoTD[i]);
    }
    return 1;
}

Hide_ArivenaLogoTD(playerid)
{
    for(new i = 0; i < 20; i++)
    {
        TextDrawHideForPlayer(playerid, ArivenaLogoTD[i]);
    }
    return 1;
}