#define COL_VANTARA         0xFFD700FF
#define VANTARA             "{FFD700}"

#define COLOR_WHITE         0xFFFFFFFF
#define COLOR_BLACK         0x000000FF

#define COLOR_RED           0xFF0000FF
#define COLOR_LIGHTRED      0xFF6666FF
#define COLOR_DARKRED       0x990000FF

#define COLOR_GREEN         0x00FF00FF
#define COLOR_LIGHTGREEN    0x66FF66FF
#define COLOR_DARKGREEN     0x009900FF

#define COLOR_BLUE          0x0000FFFF
#define COLOR_LIGHTBLUE     0x6666FFFF
#define COLOR_DARKBLUE      0x000099FF

#define COLOR_YELLOW        0xFFFF00FF
#define COLOR_LIGHTYELLOW   0xFFFF99FF
#define COLOR_DARKYELLOW    0x999900FF

#define COLOR_ORANGE        0xFFA500FF
#define COLOR_LIGHTORANGE   0xFFC966FF
#define COLOR_DARKORANGE    0xCC7A00FF

#define COLOR_PURPLE        0x8000FFFF
#define COLOR_LIGHTPURPLE   0xB266FFFF
#define COLOR_DARKPURPLE    0x4D0099FF

#define COLOR_PINK          0xFF69B4FF
#define COLOR_LIGHTPINK     0xFFB6D9FF
#define COLOR_DARKPINK      0xCC3385FF

#define COLOR_CYAN          0x00FFFFFF
#define COLOR_LIGHTCYAN     0x99FFFFFF
#define COLOR_DARKCYAN      0x009999FF

#define COLOR_LIME          0x7FFF00FF
#define COLOR_LIGHTLIME     0xB2FF66FF
#define COLOR_DARKLIME      0x4D9900FF

#define COLOR_BROWN         0xA52A2AFF
#define COLOR_LIGHTBROWN    0xC68642FF
#define COLOR_DARKBROWN     0x654321FF

#define COLOR_GREY          0x808080FF
#define COLOR_LIGHTGREY     0xC0C0C0FF
#define COLOR_DARKGREY      0x404040FF

#define COLOR_GOLD          0xFFD700FF
#define COLOR_SILVER        0xC0C0C0FF

#define COLOR_NAVY          0x000080FF
#define COLOR_MAROON        0x800000FF
#define COLOR_OLIVE         0x808000FF
#define COLOR_TEAL          0x008080FF

#define COLOR_AQUA          0x00FFFFFF
#define COLOR_VIOLET        0xEE82EEFF
#define COLOR_MAGENTA       0xFF00FFFF
#define COLOR_TURQUOISE     0x40E0D0FF
#define COLOR_SKYBLUE       0x87CEEBFF
#define COLOR_BEIGE         0xF5F5DCFF
#define COLOR_CORAL         0xFF7F50FF
#define COLOR_CRIMSON       0xDC143CFF
#define COLOR_INDIGO        0x4B0082FF
#define COLOR_KHAKI         0xF0E68CFF
#define COLOR_MINT          0x98FF98FF
#define COLOR_SALMON        0xFA8072FF
#define COLOR_TAN           0xD2B48CFF

// FORMATED COLORS
#define F_COLOR_WHITE         "{FFFFFF}"
#define F_COLOR_BLACK         "{000000}"

#define F_COLOR_RED           "{FF0000}"
#define F_COLOR_LIGHTRED      "{FF6666}"
#define F_COLOR_DARKRED       "{990000}"

#define F_COLOR_GREEN         "{00FF00}"
#define F_COLOR_LIGHTGREEN    "{66FF66}"
#define F_COLOR_DARKGREEN     "{009900}"

#define F_COLOR_BLUE          "{0000FF}"
#define F_COLOR_LIGHTBLUE     "{6666FF}"
#define F_COLOR_DARKBLUE      "{000099}"

#define F_COLOR_YELLOW        "{FFFF00}"
#define F_COLOR_LIGHTYELLOW   "{FFFF99}"
#define F_COLOR_DARKYELLOW    "{999900}"

#define F_COLOR_ORANGE        "{FFA500}"
#define F_COLOR_LIGHTORANGE   "{FFC966}"
#define F_COLOR_DARKORANGE    "{CC7A00}"

#define F_COLOR_PURPLE        "{8000FF}"
#define F_COLOR_LIGHTPURPLE   "{B266FF}"
#define F_COLOR_DARKPURPLE    "{4D0099}"

#define F_COLOR_PINK          "{FF69B4}"
#define F_COLOR_LIGHTPINK     "{FFB6D9}"
#define F_COLOR_DARKPINK      "{CC3385}"

#define F_COLOR_CYAN          "{00FFFF}"
#define F_COLOR_LIGHTCYAN     "{99FFFF}"
#define F_COLOR_DARKCYAN      "{009999}"

#define F_COLOR_LIME          "{7FFF00}"
#define F_COLOR_LIGHTLIME     "{B2FF66}"
#define F_COLOR_DARKLIME      "{4D9900}"

#define F_COLOR_BROWN         "{A52A2A}"
#define F_COLOR_LIGHTBROWN    "{C68642}"
#define F_COLOR_DARKBROWN     "{654321}"

#define F_COLOR_GREY          "{808080}"
#define F_COLOR_LIGHTGREY     "{C0C0C0}"
#define F_COLOR_DARKGREY      "{404040}"

#define F_COLOR_GOLD          "{FFD700}"
#define F_COLOR_SILVER        "{C0C0C0}"

#define F_COLOR_NAVY          "{000080}"
#define F_COLOR_MAROON        "{800000}"
#define F_COLOR_OLIVE         "{808000}"
#define F_COLOR_TEAL          "{008080}"

#define F_COLOR_AQUA          "{00FFFF}"
#define F_COLOR_VIOLET        "{EE82EE}"
#define F_COLOR_MAGENTA       "{FF00FF}"
#define F_COLOR_TURQUOISE     "{40E0D0}"
#define F_COLOR_SKYBLUE       "{87CEEB}"
#define F_COLOR_BEIGE         "{F5F5DC}"
#define F_COLOR_CORAL         "{FF7F50}"
#define F_COLOR_CRIMSON       "{DC143C}"
#define F_COLOR_INDIGO        "{4B0082}"
#define F_COLOR_KHAKI         "{F0E68C}"
#define F_COLOR_MINT          "{98FF98}"
#define F_COLOR_SALMON        "{FA8072}"
#define F_COLOR_TAN           "{D2B48C}"